### ISSUE TITLE
Testing GItHub Actions

### ISSUE THREAD

**Issue by notarock** [notarock/a_c_a_c#31]

**Comment by notarock** [comment]
Github actions, please add this

```yaml
name: "coolstreamer"
frequency: 45
allow_bits: true
extra_bots:
  - "coolbot"
  - "hypebot"

```

**Comment by notarock** [comment]
dadasd

```yaml
name: "coolstreamer"
frequency: 45
allow_bits: true
extra_bots:
  - "coolbot"
  - "hypebot"
```

**Comment by notarock** [comment]
```yaml
name: "coolstreamer"
frequency: 45
allow_bits: true
extra_bots:
  - "coolbot"
  - "hypebot"
```

**Comment by notarock** [comment]
```yaml
name: "coolstreamer"
frequency: 45
allow_bits: true
extra_bots:
  - "coolbot"
  - "hypebot"
```

**Comment by notarock** [comment]
```yml
name: "coolstreamer"
frequency: 45
allow_bits: true
extra_bots:
  - "coolbot"
  - "hypebot"
```

**Comment by notarock** [comment]
```yaml
name: "coolstreamer"
frequency: 45
allow_bits: true
extra_bots:
  - "coolbot"
  - "hypebot"
```

**Comment by notarock** [comment]
```yaml
name: "coolstreamer"
frequency: 45
allow_bits: true
extra_bots:
  - "coolbot"
  - "hypebot"
```

**Comment by notarock** [comment]
```yaml
name: "coolstreamer"
frequency: 45
allow_bits: true
extra_bots:
  - "coolbot"
  - "hypebot"

````

Some other stuff to see if it's robust

**Comment by notarock** [comment]
```yaml
name: "coolstreamer2"
frequency: 45
allow_bits: true
extra_bots:
  - "coolbot"
  - "hypebot"
```

**Comment by notarock** [comment]
name: "coolstreamer2"
frequency: 5
allow_bits: true
extra_bots:
  - "lolbot"

**Comment by notarock** [comment]
```yaml
name: "coolstreamer2"
frequency: 455
allow_bits: false
extra_bots:
  - "coolbot"
  - "lolbot"
```
